### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by carlthome** [wslihgt/pyfasst#6]
Does the package support Python 3? It doesn't seem like it does.

`pip install pyfasst`

```
Collecting pyfasst
  Using cached pyFASST-0.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l2rhg0cg/pyfasst/setup.py", line 56, in <module>
        m.Extension.__dict__ = m._Extension.__dict__
    AttributeError: attribute '__dict__' of 'type' objects is not writable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-l2rhg0cg/pyfasst/
```

**Comment by wslihgt** [comment]
Hi! I actually don't know if it works with Python 3. At the moment, the development of pyfasst is quite... well, I have not much time for it, now... 

Maybe one day I could look into it. In the meantime, I'd suggest you to check the "original" FASST framework, as they have issued newer optimized versions, with possible Python bindings. Maybe you'll find what you are looking for there!

Cheers,
Jean-Louis

**Comment by ph-preux** [comment]
Hi,

I've just discovered your software. Seems really great, but that not install in the first place: same error as above. However, I succeeded in fixing it (at least on my Ubuntu 16.04): this is very simple: remove lines 54 to 56 in file setup.py
I install with pip or pip3: this works well in both cases. (Need to sudo pip.)
But then, the package crashes during the import:

$ python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import pyfasst.audioModel as am
> > > Using scipy.io.wavfile
> > > pyfasst/tftransforms/nsgt/**init**.py:37: UserWarning: Audio IO routines (scikits.audio module) could not be imported
> > >   warn("Audio IO routines (scikits.audio module) could not be imported")
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "pyfasst/audioModel.py", line 42, in <module>
> > >     import SeparateLeadStereo.SeparateLeadStereoTF as SLS
> > >   File "pyfasst/SeparateLeadStereo/SeparateLeadStereoTF.py", line 25, in <module>
> > >     from .tracking._tracking import viterbiTracking as viterbiTrackingArray
> > > ImportError: No module named _tracking

Then, I don't know what to do (and I am not fluent in python...).
Cheers,
Philippe

**Comment by carlthome** [comment]
If we could start by getting https://github.com/wslihgt/pyfasst/pull/9 up and running I'd like to take a quick stab at getting Python 3 compatibility working.
