### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an index.

### ISSUE THREAD

**Issue by h82lin** [wslihgt/pyfasst#7]
```
Reading and Writing WAV files with audiolab
('Computing the chosen signal representation:', 'stft')
Traceback (most recent call last):
  File "try.py", line  5, in <module>
    verbose=1, iter_num=50)
  File "build/bdist.linux-x86_64/egg/pyfasst/audioModel.py", line 2484, in __init__
  File "build/bdist.linux-x86_64/egg/pyfasst/audioModel.py", line 2339, in __init__
  File "build/bdist.linux-x86_64/egg/pyfasst/audioModel.py", line 278, in comp_transf_Cx
  File "build/bdist.linux-x86_64/egg/pyfasst/tftransforms/stft.py", line 382, in computeTransform
  File "build/bdist.linux-x86_64/egg/pyfasst/tftransforms/stft.py", line 47, in stft
TypeError: 'float' object cannot be interpreted as an index
```

The error message above appears whenever I try to execute to following code:

```
import pyfasst.audioModel as am
filename = 'music.wav'
model = am.MultiChanNMFConv(audio=filename,
                nbComps=2, nbNMFComps=32, spatial_rank=1,
                verbose=1, iter_num=50)
model.estim_param_a_post_model()
model.separate_spat_comps(dir_results='data/')
```
I have been stuck on this for 2 days. I think it has to do with the "audio" parameter in the MultiChanNMFConv class. However, I even tried the audio from http://bass-db.gforge.inria.fr/fasst/ and the same thing happened.  Do you know why this is occurring?

**Comment by akshayaCap** [comment]
Did you find solution to this?

**Comment by h82lin** [comment]
No, unfortunately not :(

**Comment by shoegazerstella** [comment]
I made it work somehow.
Clone the repository so you can edit the code.
You need to import the modules from the cloned repository.

Go to `pyfasst/tftransforms/stft.py` and edit the following lines:

40 `numberFrames = int(np.ceil(lengthData / np.double(hopsize)) + 2)`
43 `newLengthData = int((numberFrames-1) * hopsize + lengthWindow)`
47 `data = np.concatenate((np.zeros(int(lengthWindow/2.0)), data))`
56 `STFT = np.zeros([int(numberFrequencies), numberFrames], dtype=complex)`
123 `data = data[int(lengthWindow/2.0):]`
124 `normalisationSeq = normalisationSeq[int(lengthWindow/2.0):]`
